
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 666528
	#The name of the modpack
	modpackName = "Tyrannical Pack"
	#The version of the modpack
	modpackVersion = "0.0.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

